[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules','lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
remapping = [

    ]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.test]
src = 'test/foundry'
via_ir = false