# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.test]
src = 'src'
out = 'out'
libs = ['node_modules','lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
remapping = [
                '@openzeppelin/=node_modules/@openzeppelin/',
                'ds-test/=lib/forge-std/lib/ds-test/src/',
                'forge-std/=lib/forge-std/src/',
                'hardhat/=node_modules/hardhat/',
                'openzeppelin-contracts-06/=node_modules/openzeppelin-contracts-06/',
                'openzeppelin-contracts-08/=node_modules/openzeppelin-contracts-08/'
    ]
via_ir = false
fs_permissions = [{ access = "read", path = "./out"}]

# Gas reports
gas_reports = ["*"]

[rpc_endpoints]
localhost = '${LOCALHOST}'
mumbai = '${POLYGON_TESTNET_RPC_URL}'
goerli = '${GOERLI_TESTNET_RPC_URL}'
